test

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -79,7 +79,10 @@ jobs:
     - name: Prepare and compile dependencies
       run: python .ci/cue.py prepare
     - name: Build main module
-      run: python .ci/cue.py build
+      run: |
+        # First pass will most likely fail due to issues with msi
+        python .ci/cue.py build || true
+        python .ci/cue.py build
     - name: Run main module tests
       run: python .ci/cue.py test
     - name: Upload tapfiles Artifact
